# prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# swtich panes with Shift+<arrow>
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

# switch windows with Alt+<arrow>
bind -n M-Left previous-window
bind -n M-Right next-window

# mouse mode
setw -g mouse on

# split window
bind-key v split-window -h
bind-key h split-window -v
